import { Field } from '@/types';

// Campos para Revision Semanal
export const fluidosSemanalFields: Record<'MOTO', Field[]> = {
    // CARRO: [
    //     {
    //         id: 'trenDel',
    //         label: 'Tren Delantero',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'trenDel_archivo',
    //         label: 'Tren Delantero',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'trenTra',
    //         label: 'Tren Trasero',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'trenTra_archivo',
    //         label: 'Tren Trasero',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'motor',
    //         label: 'Motor',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'motor_archivo',
    //         label: 'Motor',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'caja',
    //         label: 'Caja',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'caja_archivo',
    //         label: 'Caja',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'tablero',
    //         label: 'Tablero',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'tablero_archivo',
    //         label: 'Tablero',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'carroceriaDer',
    //         label: 'Carroceria lado Derecho',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'carroceriaDer_archivo',
    //         label: 'Carroceria lado Derecho',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'carroceriaIzq',
    //         label: 'Carroceria lado Izquierdo',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'carroceriaIzq_archivo',
    //         label: 'Carroceria lado Izquierdo',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'lucesDel',
    //         label: 'Luces Delanteras',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'lucesDel_archivo',
    //         label: 'Luces Delanteras',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'lucesTra',
    //         label: 'Luces Traseras',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'lucesTra_archivo',
    //         label: 'Luces Traseras',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'cauchosDel',
    //         label: 'Cauchos Delanteros',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'cauchosDel_archivo',
    //         label: 'Cauchos Delanteros',
    //         type: 'file',
    //         required: true,
    //     },
    //     {
    //         id: 'cauchosTra',
    //         label: 'Cauchos Traseros',
    //         type: 'text',
    //         required: true,
    //     },
    //     {
    //         id: 'cauchosTra_archivo',
    //         label: 'Cauchos Traseros',
    //         type: 'file',
    //         required: true,
    //     },
    // ],
    MOTO: [
        {
            id: 'cauchoDel_archivo',
            label: 'Caucho Delantero',
            type: 'file',
            required: true,
        },
        {
            id: 'cauchoTra_archivo',
            label: 'Caucho Trasero',
            type: 'file',
            required: true,
        },
        {
            id: 'tacometro_archivo',
            label: 'Tacometro',
            type: 'file',
            required: true,
        },
        {
            id: 'luzAlt_archivo',
            label: 'Luz Alta',
            type: 'file',
            required: true,
        },
        {
            id: 'luzBaj_archivo',
            label: 'Luz Baja',
            type: 'file',
            required: true,
        },
        {
            id: 'stop_archivo',
            label: 'Stop',
            type: 'file',
            required: true,
        },
        {
            id: 'relacion_archivo',
            label: 'Relación',
            type: 'file',
            required: true,
        },
        {
            id: 'pito_archivo',
            label: 'Pito',
            type: 'file',
            required: true,
        },
        {
            id: 'placa_archivo',
            label: 'Placa',
            type: 'file',
            required: true,
        },
        {
            id: 'asiento_archivo',
            label: 'Asiento',
            type: 'file',
            required: true,
        },
        {
            id: 'crucesDel_archivo',
            label: 'Cruces Delanteros',
            type: 'file',
            required: true,
        },
        {
            id: 'crucesTra_archivo',
            label: 'Cruces Traseros',
            type: 'file',
            required: true,
        },
        {
            id: 'motor_archivo',
            label: 'Motor',
            type: 'file',
            required: true,
        },
        {
            id: 'cajon_archivo',
            label: 'Cajon',
            type: 'file',
            required: true,
        },
        {
            id: 'pastillas_archivo',
            label: 'Pastillas',
            type: 'file',
            required: true,
        },
        {
            id: 'bandas_archivo',
            label: 'Bandas (Varilla)',
            type: 'file',
            required: true,
        },
        {
            id: 'retrovisores_archivo',
            label: 'Retrovisores',
            type: 'file',
            required: true,
        },
        {
            id: 'latIzq_archivo',
            label: 'Lateral Izquierdo',
            type: 'file',
            required: true,
        },
        {
            id: 'ladDer_archivo',
            label: 'Lateral Derecho',
            type: 'file',
            required: true,
        },
        {
            id: 'bateria_archivo',
            label: 'Bateria',
            type: 'file',
            required: true,
        },
        // OBSERVACION
        {
            id: 'observacion_general',
            label: 'Observacion General',
            type: 'text',
            required: true,
        },
    ],
};
