import { Field } from '@/types';

// Campos para Revision Semanal
export const fluidosSemanalFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: 'trenDel',
            label: 'Tren Delantero',
            type: 'text',
            required: false,
        },
        {
            id: 'trenDel_archivo',
            label: 'Tren Delantero',
            type: 'file',
            required: false,
        },
        {
            id: 'trenTra',
            label: 'Tren Trasero',
            type: 'text',
            required: false,
        },
        {
            id: 'trenTra_archivo',
            label: 'Tren Trasero',
            type: 'file',
            required: false,
        },
        {
            id: 'motor',
            label: 'Motor',
            type: 'text',
            required: false,
        },
        {
            id: 'motor_archivo',
            label: 'Motor',
            type: 'file',
            required: false,
        },
        {
            id: 'caja',
            label: 'Caja',
            type: 'text',
            required: false,
        },
        {
            id: 'caja_archivo',
            label: 'Caja',
            type: 'file',
            required: false,
        },
        {
            id: 'tablero',
            label: 'Tablero',
            type: 'text',
            required: false,
        },
        {
            id: 'tablero_archivo',
            label: 'Tablero',
            type: 'file',
            required: false,
        },
        {
            id: 'carroceriaDer',
            label: 'Carroceria lado Derecho',
            type: 'text',
            required: false,
        },
        {
            id: 'carroceriaDer_archivo',
            label: 'Carroceria lado Derecho',
            type: 'file',
            required: false,
        },
        {
            id: 'carroceriaIzq',
            label: 'Carroceria lado Izquierdo',
            type: 'text',
            required: false,
        },
        {
            id: 'carroceriaIzq_archivo',
            label: 'Carroceria lado Izquierdo',
            type: 'file',
            required: false,
        },
        {
            id: 'lucesDel',
            label: 'Luces Delanteras',
            type: 'text',
            required: false,
        },
        {
            id: 'lucesDel_archivo',
            label: 'Luces Delanteras',
            type: 'file',
            required: false,
        },
        {
            id: 'lucesTra',
            label: 'Luces Traseras',
            type: 'text',
            required: false,
        },
        {
            id: 'lucesTra_archivo',
            label: 'Luces Traseras',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchosDel',
            label: 'Cauchos Delanteros',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchosDel_archivo',
            label: 'Cauchos Delanteros',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchosTra',
            label: 'Cauchos Traseros',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchosTra_archivo',
            label: 'Cauchos Traseros',
            type: 'file',
            required: false,
        },
    ],
    MOTO: [
        {
            id: 'cauchoDel_archivo',
            label: 'Caucho Delantero',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchoTra_archivo',
            label: 'Caucho Trasero',
            type: 'file',
            required: false,
        },
        {
            id: 'tacometro_archivo',
            label: 'Tacometro',
            type: 'file',
            required: false,
        },
        {
            id: 'luzAlt_archivo',
            label: 'Luz Alta',
            type: 'file',
            required: false,
        },
        {
            id: 'luzBaj_archivo',
            label: 'Luz Baja',
            type: 'file',
            required: false,
        },
        {
            id: 'stop_archivo',
            label: 'Stop',
            type: 'file',
            required: false,
        },
        {
            id: 'relacion_archivo',
            label: 'Relación',
            type: 'file',
            required: false,
        },
        {
            id: 'pito_archivo',
            label: 'Pito',
            type: 'file',
            required: false,
        },
        {
            id: 'placa_archivo',
            label: 'Placa',
            type: 'file',
            required: false,
        },
        {
            id: 'asiento_archivo',
            label: 'Asiento',
            type: 'file',
            required: false,
        },
        {
            id: 'crucesDel_archivo',
            label: 'Cruces Delanteros',
            type: 'file',
            required: false,
        },
        {
            id: 'crucesTra_archivo',
            label: 'Cruces Traseros',
            type: 'file',
            required: false,
        },
        {
            id: 'motor_archivo',
            label: 'Motor',
            type: 'file',
            required: false,
        },
        {
            id: 'cajon_archivo',
            label: 'Cajon',
            type: 'file',
            required: false,
        },
        {
            id: 'pastillas_archivo',
            label: 'Pastillas',
            type: 'file',
            required: false,
        },
        {
            id: 'bandas_archivo',
            label: 'Bandas (Varilla)',
            type: 'file',
            required: false,
        },
        {
            id: 'retrovisores_archivo',
            label: 'Retrovisores',
            type: 'file',
            required: false,
        },
        {
            id: 'latIzq_archivo',
            label: 'Lateral Izquierdo',
            type: 'file',
            required: false,
        },
        {
            id: 'ladDer_archivo',
            label: 'Lateral Derecho',
            type: 'file',
            required: false,
        },
        {
            id: 'bateria_archivo',
            label: 'Bateria',
            type: 'file',
            required: false,
        },
        // OBSERVACION
        {
            id: 'observacion_general',
            label: 'Observacion General',
            type: 'text',
            required: false,
        },
    ],
};
