import { Field } from '@/hooks/useFormLogic';
import { SurtidoField } from '@/types';

// Campos para el formulario de Expediente
export const expedienteTecnicoFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: '1',
            label: 'Kilometraje',
            type: 'text',
            placeholder: 'Ej: 12.345',
            required: false,
        },
        {
            id: '2',
            label: 'Marca del Aceite',
            type: 'text',
            placeholder: 'Ej: Castrol',
            required: false,
        },
        {
            id: '3',
            label: 'Marca de Valvulina',
            type: 'text',
            placeholder: 'Ej: Mobil',
            required: false,
        },
        {
            id: '4',
            label: 'Marca del Refrigerante',
            type: 'text',
            placeholder: 'Ej: Motul',
            required: false,
        },
        {
            id: '5',
            label: 'Posee Computadora Bloqueada',
            type: 'text',
            placeholder: 'SI / NO',
            required: false,
        },
        {
            id: '6',
            label: 'Tipo de Frenos',
            type: 'text',
            placeholder: 'Ej: Disco, Tambor, ABS',
            required: false,
        },
        {
            id: '7',
            label: 'Tipo de Distribución de Motor',
            type: 'text',
            placeholder: 'Ej: Cadena, Correa, Engranajes',
            required: false,
        },
        {
            id: '8',
            label: 'Sistema de Enfriamiento',
            type: 'text',
            placeholder: 'Ej: Aire, Líquido',
            required: false,
        },
        {
            id: '9',
            label: 'Sistema de Inyección',
            type: 'text',
            placeholder: 'Ej: Gasolina, Eléctrico, Diésel',
            required: false,
        },
        {
            id: '10',
            label: 'Tipo de Cauchos',
            type: 'text',
            placeholder: 'Ej: Medida, Marca',
            required: false,
        },
    ],
    MOTO: [
        {
            id: '1',
            label: 'Kilometraje',
            type: 'text',
            placeholder: 'Ej: 12.345',
            required: false,
        },
        {
            id: '2',
            label: 'Marca del Aceite',
            type: 'text',
            placeholder: 'Ej: Motul',
            required: false,
        },
        {
            id: '3',
            label: 'Tipo de Motor',
            type: 'text',
            placeholder: 'Ej: 4 tiempos, 2 tiempos',
            required: false,
        },
        {
            id: '4',
            label: 'Cilindrada',
            type: 'text',
            placeholder: 'Ej: 150cc, 250cc',
            required: false,
        },
        {
            id: '5',
            label: 'Sistema de Enfriamiento',
            type: 'text',
            placeholder: 'Ej: Aire, Líquido',
            required: false,
        },
        {
            id: '6',
            label: 'Tipo de Frenos',
            type: 'text',
            placeholder: 'Ej: Disco, Tambor',
            required: false,
        },
        {
            id: '7',
            label: 'Tipo de Cauchos',
            type: 'text',
            placeholder: 'Ej: Medida, Marca',
            required: false,
        },
    ],
};

// Campos para el formulario de Permisologia
export const permisologiaFields: Field[] = [
    {
        id: 'titulo_archivo',
        label: 'Título del Vehículo',
        type: 'file',
        required: false,
    },

    {
        id: 'seguro',
        label: 'Seguro RCV',
        type: 'date',
        required: false,
    },
    {
        id: 'seguro_archivo',
        label: 'Documento de Seguro RCV',
        type: 'file',
        required: false,
    },

    {
        id: 'roct',
        label: 'Roct',
        type: 'date',
        required: false,
    },
    {
        id: 'roct_archivo',
        label: 'Documento Roct',
        type: 'file',
        required: false,
    },

    {
        id: 'permisoRotReg',
        label: 'Permiso de Rotulado Regional',
        type: 'date',
        required: false,
    },
    {
        id: 'permisoRotReg_archivo',
        label: 'Documento Rotulado Regional',
        type: 'file',
        required: false,
    },

    {
        id: 'permisoRotNac',
        label: 'Permiso de Rotulado Nacional',
        type: 'date',
        required: false,
    },
    {
        id: 'permisoRotNac_archivo',
        label: 'Documento Rotulado Nacional',
        type: 'file',
        required: false,
    },

    {
        id: 'salvoconducto',
        label: 'Salvoconducto',
        type: 'date',
        required: false,
    },
    {
        id: 'salvoconducto_archivo',
        label: 'Documento Salvoconducto',
        type: 'file',
        required: false,
    },

    {
        id: 'permisoAliMed',
        label: 'Permiso de Alimentos y Medicamentos',
        type: 'date',
        required: false,
    },
    {
        id: 'permisoAliMed_archivo',
        label: 'Documento Alimentos y Medicamentos',
        type: 'file',
        required: false,
    },
];

// Campos para el formulario de Accesorios
export const accesoriosFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: '1',
            label: 'Caja de Herramienta',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Conos de seguridad',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '3',
            label: 'Cuña',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '3', label: 'Malo' },
                { value: '4', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '4',
            label: 'Extintor',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '5',
            label: 'Gato',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '6',
            label: 'Llave de cruz',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '7',
            label: 'Linterna',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '8',
            label: 'Caucho de Repuesto',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
    MOTO: [
        {
            id: '1',
            label: 'Caja de Herramienta',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Linterna',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
};

// Campos para el formulario de Piezas Revisadas
export const piezasRevisadasFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: '1',
            label: 'Aire Acondicionado',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Caucho Delantero Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '3',
            label: 'Caucho Delantero Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '4',
            label: 'Caucho Tracero Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '5',
            label: 'Caucho Tracero Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '6',
            label: 'Cepillos Limpia Parabrisas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '7',
            label: 'Cerraduras de Puertas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '8',
            label: 'Cinturones de Segurida',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '9',
            label: 'Espejo Interior de Cabina',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '10',
            label: 'Espejo Retovisor Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '11',
            label: 'Espejo Retovisor Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '12',
            label: 'Estado de la Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '13',
            label: 'Estado de los Bornes de Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '14',
            label: 'Estado de la Carroceria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '15',
            label: 'Estado del Parachoques',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '16',
            label: 'Estado de la Pintura',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '17',
            label: 'Estado del Guardapolvos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '18',
            label: 'Estados de los Recipientes de Fluidos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '19',
            label: 'Estado del Sistema de Enfriamiento',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '20',
            label: 'Gomas de las Puertas y Ventanas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '21',
            label: 'Luces de los Cruces Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '22',
            label: 'Luces de los Cruces Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '23',
            label: 'Luces de los Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '24',
            label: 'Luces de Neblina',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '25',
            label: 'Luces de los Retroceso',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '26',
            label: 'Luces Delanteras Altas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '27',
            label: 'Luces Delanteras Bajas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '28',
            label: 'Luces Intermitentes Delanteras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '29',
            label: 'Luces Intermitentes Traceras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '30',
            label: 'Luces Internas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '31',
            label: 'Luces Testigo',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '32',
            label: 'Manijas de las Puertas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '33',
            label: 'Manijas de las Ventanas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '34',
            label: 'Vidrios Laterales Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '35',
            label: 'Vidrios Laterales Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '36',
            label: 'Vidrio Parabrisas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '37',
            label: 'Pito',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '38',
            label: 'Revisión de Esparragos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '39',
            label: 'Tablero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '40',
            label: 'Tapetes',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '41',
            label: 'Tapicería',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
    MOTO: [
        {
            id: '1',
            label: 'Caucho Delantero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Caucho Tracero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '3',
            label: 'Espejo Retovisor Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '4',
            label: 'Espejo Retovisor Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '5',
            label: 'Estado de la Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '6',
            label: 'Estado de los Bornes de Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '7',
            label: 'Estado de la Carroceria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '8',
            label: 'Estado de la Pintura',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '9',
            label: 'Estado del Guardapolvos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '10',
            label: 'Estados de los Recipientes de Fluidos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '11',
            label: 'Estado del Sistema de Enfriamiento',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '12',
            label: 'Luces de los Cruces Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '13',
            label: 'Luces de los Cruces Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '14',
            label: 'Luces de los Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '15',
            label: 'Luces Exploradoras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '16',
            label: 'Luces Delanteras Altas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '17',
            label: 'Luces Delanteras Bajas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '18',
            label: 'Luces Intermitentes Delanteras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '19',
            label: 'Luces Intermitentes Traceras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '20',
            label: 'Pito',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '21',
            label: 'Tablero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
};

// Campos para Fluidos para Revisar y revisionFluidos
export const fluidosPorRevisarFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: 'aceite',
            label: 'Aceite de Motor',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
        {
            id: 'refrigerante',
            label: 'Refrigerante o Agua',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
        {
            id: 'direccion',
            label: 'Líquido de Dirección',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
        {
            id: 'frenos',
            label: 'Liga de Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
    ],
    MOTO: [
        {
            id: 'aceite',
            label: 'Aceite de Motor',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
        {
            id: 'frenos',
            label: 'Liga de Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Full' },
                { value: '1', label: 'Normal' },
                { value: '2', label: 'Bajo' },
            ],
            required: false,
        },
        {
            id: 'cauchos',
            label: 'Vida de los Cauchos',
            type: 'select',
            options: [
                { value: '0', label: 'Nuevos' },
                { value: '1', label: 'Media Vida' },
                { value: '2', label: 'Lisos' },
            ],
            required: false,
        },
        {
            id: 'relacion',
            label: 'Vida de la Relación',
            type: 'select',
            options: [
                { value: '0', label: 'Nueva' },
                { value: '1', label: 'Media Vida' },
                { value: '2', label: 'Mala' },
            ],
            required: false,
        },
    ],
};

// Campos para Revision Semanal
export const fluidosSemanalFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: 'trenDel',
            label: 'Tren Delantero',
            type: 'text',
            required: false,
        },
        {
            id: 'trenDel_archivo',
            label: 'Tren Delantero',
            type: 'file',
            required: false,
        },
        {
            id: 'trenTra',
            label: 'Tren Trasero',
            type: 'text',
            required: false,
        },
        {
            id: 'trenTra_archivo',
            label: 'Tren Trasero',
            type: 'file',
            required: false,
        },
        {
            id: 'motor',
            label: 'Motor',
            type: 'text',
            required: false,
        },
        {
            id: 'motor_archivo',
            label: 'Motor',
            type: 'file',
            required: false,
        },
        {
            id: 'caja',
            label: 'Caja',
            type: 'text',
            required: false,
        },
        {
            id: 'caja_archivo',
            label: 'Caja',
            type: 'file',
            required: false,
        },
        {
            id: 'tablero',
            label: 'Tablero',
            type: 'text',
            required: false,
        },
        {
            id: 'tablero_archivo',
            label: 'Tablero',
            type: 'file',
            required: false,
        },
        {
            id: 'carroceriaDer',
            label: 'Carroceria lado Derecho',
            type: 'text',
            required: false,
        },
        {
            id: 'carroceriaDer_archivo',
            label: 'Carroceria lado Derecho',
            type: 'file',
            required: false,
        },
        {
            id: 'carroceriaIzq',
            label: 'Carroceria lado Izquierdo',
            type: 'text',
            required: false,
        },
        {
            id: 'carroceriaIzq_archivo',
            label: 'Carroceria lado Izquierdo',
            type: 'file',
            required: false,
        },
        {
            id: 'lucesDel',
            label: 'Luces Delanteras',
            type: 'text',
            required: false,
        },
        {
            id: 'lucesDel_archivo',
            label: 'Luces Delanteras',
            type: 'file',
            required: false,
        },
        {
            id: 'lucesTra',
            label: 'Luces Traseras',
            type: 'text',
            required: false,
        },
        {
            id: 'lucesTra_archivo',
            label: 'Luces Traseras',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchosDel',
            label: 'Cauchos Delanteros',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchosDel_archivo',
            label: 'Cauchos Delanteros',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchosTra',
            label: 'Cauchos Traseros',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchosTra_archivo',
            label: 'Cauchos Traseros',
            type: 'file',
            required: false,
        },
    ],
    MOTO: [
        {
            id: 'cauchoDel',
            label: 'Caucho Delantero',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchoDel_archivo',
            label: 'Caucho Delantero',
            type: 'file',
            required: false,
        },
        {
            id: 'cauchoTra',
            label: 'Caucho Trasero',
            type: 'text',
            required: false,
        },
        {
            id: 'cauchoTra_archivo',
            label: 'Caucho Trasero',
            type: 'file',
            required: false,
        },
        {
            id: 'foco',
            label: 'Foco',
            type: 'text',
            required: false,
        },
        {
            id: 'foco_archivo',
            label: 'Foco',
            type: 'file',
            required: false,
        },
        {
            id: 'stop',
            label: 'Stop',
            type: 'text',
            required: false,
        },
        {
            id: 'stop_archivo',
            label: 'Stop',
            type: 'file',
            required: false,
        },
        {
            id: 'aceite',
            label: 'Aceite',
            type: 'text',
            required: false,
        },
        {
            id: 'aceite_archivo',
            label: 'Aceite',
            type: 'file',
            required: false,
        },
        {
            id: 'relacion',
            label: 'Relación',
            type: 'text',
            required: false,
        },
        {
            id: 'relacion_archivo',
            label: 'Relación',
            type: 'file',
            required: false,
        },
        {
            id: 'asiento',
            label: 'Asiento',
            type: 'text',
            required: false,
        },
        {
            id: 'asiento_archivo',
            label: 'Asiento',
            type: 'file',
            required: false,
        },
        {
            id: 'crucesDel',
            label: 'Cruces Delanteros',
            type: 'text',
            required: false,
        },
        {
            id: 'crucesDel_archivo',
            label: 'Cruces Delanteros',
            type: 'file',
            required: false,
        },
        {
            id: 'crucesTra',
            label: 'Cruces Traseros',
            type: 'text',
            required: false,
        },
        {
            id: 'crucesTra_archivo',
            label: 'Cruces Traseros',
            type: 'file',
            required: false,
        },
        {
            id: 'motor',
            label: 'Motor',
            type: 'text',
            required: false,
        },
        {
            id: 'motor_archivo',
            label: 'Motor',
            type: 'file',
            required: false,
        },
        {
            id: 'retrovisores',
            label: 'Retrovisores',
            type: 'text',
            required: false,
        },
        {
            id: 'retrovisores_archivo',
            label: 'Retrovisores',
            type: 'file',
            required: false,
        },
    ],
};

export const getAsignacionFields = (users: { id: string | number; name: string }[]): Field[] => {
    const userOptions = users.map((u) => ({ label: u.name, value: String(u.id) }));

    const additionalUserFields: Field[] = Array.from({ length: 3 }, (_, i) => ({
        id: `user_id_adicional_${i + 1}`,
        label: `Usuario adicional ${i + 1}`,
        type: 'select',
        options: userOptions,
        required: false,
    }));

    return [
        {
            id: 'user_id',
            label: 'Usuario principal',
            type: 'select',
            options: userOptions,
            required: true,
        },
        ...additionalUserFields,
        {
            id: 'kilometraje',
            label: 'Kilometraje actual',
            type: 'text',
            placeholder: 'Ej. 123456',
            required: false,
        },
        {
            id: 'foto_kilometraje',
            label: 'Foto del Kilometraje',
            type: 'file',
            required: false,
        },
    ];
};

// Campos para Surtidos
export const fields: SurtidoField[] = [
    {
        id: 'kilometraje',
        label: 'Kilometraje actual',
        type: 'number',
        placeholder: 'Ej: 12500',
        required: true,
    },
    {
        id: 'litros',
        label: 'Litros surtidos',
        type: 'number',
        placeholder: 'Ej: 20',
        required: true,
    },
    {
        id: 'observacion',
        label: 'Observación',
        type: 'textarea',
        placeholder: 'Observaciones adicionales...',
        required: false,
    },
];
