import { Field } from '@/types';

// Campos para el formulario de Piezas Revisadas
export const piezasRevisadasFields: Record<'CARRO' | 'MOTO', Field[]> = {
    CARRO: [
        {
            id: '1',
            label: 'Aire Acondicionado',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Caucho Delantero Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '3',
            label: 'Caucho Delantero Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '4',
            label: 'Caucho Tracero Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '5',
            label: 'Caucho Tracero Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '6',
            label: 'Cepillos Limpia Parabrisas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '7',
            label: 'Cerraduras de Puertas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '8',
            label: 'Cinturones de Segurida',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '9',
            label: 'Espejo Interior de Cabina',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '10',
            label: 'Espejo Retovisor Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '11',
            label: 'Espejo Retovisor Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '12',
            label: 'Estado de la Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '13',
            label: 'Estado de los Bornes de Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '14',
            label: 'Estado de la Carroceria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '15',
            label: 'Estado del Parachoques',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '16',
            label: 'Estado de la Pintura',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '17',
            label: 'Estado del Guardapolvos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '18',
            label: 'Estados de los Recipientes de Fluidos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '19',
            label: 'Estado del Sistema de Enfriamiento',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '20',
            label: 'Gomas de las Puertas y Ventanas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '21',
            label: 'Luces de los Cruces Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '22',
            label: 'Luces de los Cruces Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '23',
            label: 'Luces de los Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '24',
            label: 'Luces de Neblina',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '25',
            label: 'Luces de los Retroceso',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '26',
            label: 'Luces Delanteras Altas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '27',
            label: 'Luces Delanteras Bajas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '28',
            label: 'Luces Intermitentes Delanteras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '29',
            label: 'Luces Intermitentes Traceras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '30',
            label: 'Luces Internas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '31',
            label: 'Luces Testigo',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '32',
            label: 'Manijas de las Puertas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '33',
            label: 'Manijas de las Ventanas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '34',
            label: 'Vidrios Laterales Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '35',
            label: 'Vidrios Laterales Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '36',
            label: 'Vidrio Parabrisas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '37',
            label: 'Pito',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '38',
            label: 'Revisión de Esparragos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '39',
            label: 'Tablero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '40',
            label: 'Tapetes',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '41',
            label: 'Tapicería',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
    MOTO: [
        {
            id: '1',
            label: 'Caucho Delantero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '2',
            label: 'Caucho Tracero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '3',
            label: 'Espejo Retovisor Der.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '4',
            label: 'Espejo Retovisor Izq.',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '5',
            label: 'Estado de la Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '6',
            label: 'Estado de los Bornes de Bateria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '7',
            label: 'Estado de la Carroceria',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '8',
            label: 'Estado de la Pintura',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '9',
            label: 'Estado del Guardapolvos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '10',
            label: 'Estados de los Recipientes de Fluidos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '11',
            label: 'Estado del Sistema de Enfriamiento',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '12',
            label: 'Luces de los Cruces Delanteros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '13',
            label: 'Luces de los Cruces Traceros',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '14',
            label: 'Luces de los Frenos',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '15',
            label: 'Luces Exploradoras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '16',
            label: 'Luces Delanteras Altas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '17',
            label: 'Luces Delanteras Bajas',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '18',
            label: 'Luces Intermitentes Delanteras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '19',
            label: 'Luces Intermitentes Traceras',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '20',
            label: 'Pito',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
        {
            id: '21',
            label: 'Tablero',
            type: 'select',
            options: [
                { value: '0', label: 'Bueno' },
                { value: '1', label: 'Regular' },
                { value: '2', label: 'Malo' },
                { value: '3', label: 'No posee' },
            ],
            required: false,
        },
    ],
};
